package com.krafttools.pulsekraft.net

import java.io.File
import java.net.InetAddress
import java.net.ServerSocket
import java.util.concurrent.CountDownLatch
import java.util.concurrent.TimeUnit
import javax.net.ssl.KeyManagerFactory
import javax.net.ssl.SSLContext
import javax.net.ssl.SSLServerSocket
import javax.net.ssl.SSLSocket
import javax.net.ssl.TrustManager
import javax.net.ssl.X509TrustManager
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Assume.assumeTrue
import org.junit.BeforeClass
import org.junit.Test

/**
 * The socket, against a real one.
 *
 * ## Why this file exists
 *
 * Everything above this layer was tested and the socket was not, and the
 * socket is where the claims this app makes about itself are kept. The
 * receive buffer is set before connect precisely so the app can read back
 * what the kernel actually granted and check its own results against it
 * — a promise that cannot be verified at all by a test that never opens
 * a socket.
 *
 * ## Why a local server and not Cloudflare
 *
 * A test against the real edge would be slow, would cost somebody data,
 * and would fail for reasons that have nothing to do with this code. A
 * local TLS server is deterministic and free, and it can be made to do
 * things the real edge only does occasionally — send `100 Continue`
 * first, truncate the body, declare a length it does not deliver.
 *
 * The certificate is generated by `keytool` when the suite first runs,
 * into the build directory, and thrown away. Nothing binary is checked
 * in and no credential is committed: a test keystore in a repository is
 * a test keystore somebody eventually mistakes for a real one.
 */
class TransportSocketTest {

    companion object {
        private lateinit var serverContext: SSLContext

        /** Body the server sends, and the shape of the response. */
        private const val BODY_BYTES = 64 * 1024

        @BeforeClass
        @JvmStatic
        fun makeCertificate() {
            val keytool = File(
                System.getProperty("java.home"),
                "bin/keytool",
            )
            assumeTrue(
                "keytool is needed to make a throwaway certificate",
                keytool.canExecute(),
            )

            val dir = File("build/test-tls").apply { mkdirs() }
            val store = File(dir, "test.p12")
            val password = "throwaway"

            if (!store.exists()) {
                val result = ProcessBuilder(
                    keytool.absolutePath,
                    "-genkeypair",
                    "-alias", "test",
                    "-keyalg", "RSA",
                    "-keysize", "2048",
                    "-validity", "1",
                    "-dname", "CN=localhost",
                    "-storetype", "PKCS12",
                    "-keystore", store.absolutePath,
                    "-storepass", password,
                    "-keypass", password,
                ).redirectErrorStream(true).start()
                result.inputStream.readBytes()
                assumeTrue(
                    "keytool failed to make a certificate",
                    result.waitFor(60, TimeUnit.SECONDS) && result.exitValue() == 0,
                )
            }

            val keyStore = java.security.KeyStore.getInstance("PKCS12").apply {
                FileInputStreamOrNull(store)?.use { load(it, password.toCharArray()) }
            }
            val keyManager = KeyManagerFactory.getInstance(
                KeyManagerFactory.getDefaultAlgorithm(),
            ).apply {
                init(keyStore, password.toCharArray())
            }
            serverContext = SSLContext.getInstance("TLS").apply {
                init(keyManager.keyManagers, null, null)
            }
        }

        private fun FileInputStreamOrNull(f: File) = if (f.exists()) f.inputStream() else null
    }

    // -------------------------------------------------------------- the tests

    @Test
    fun `the granted receive buffer is read back, not the requested one`() {
        // The promise the whole result screen's self-check rests on. The
        // kernel may refuse the request and allocates twice what it is
        // given, so the number that matters is the one that comes back.
        LocalEdge(body = BODY_BYTES).use { edge ->
            MeasuredConnection(host = "127.0.0.1", port = edge.port).use { connection ->
                connection.connect(
                    requestedReceiveBuffer = 4 * 1024 * 1024,
                    connectTimeoutMs = 5_000,
                    readTimeoutMs = 5_000,
                    tlsFactory = trustAnything(),
                )
                assertTrue(
                    "the granted buffer was never read back",
                    connection.grantedReceiveBuffer > 0,
                )
                // Whatever the number is, the self-check is answerable
                // from it — which is the property that matters.
                assertNotNull(
                    BufferCeilingProbe(connection.grantedReceiveBuffer),
                )
            }
        }
    }

    @Test
    fun `a request and its response cross a real socket`() {
        var seen = 0
        LocalEdge(body = BODY_BYTES).use { edge ->
            MeasuredConnection(host = "127.0.0.1", port = edge.port).use { connection ->
                connection.connect(1024 * 1024, 5_000, 5_000, tlsFactory = trustAnything())
                val result = connection.timedExchange("/__down?bytes=$BODY_BYTES")
                assertEquals("the body was not counted", BODY_BYTES.toLong(), result.bytes)
                assertTrue("the elapsed time was not measured", result.nanos > 0)
                seen = edge.requests
            }
        }
        assertEquals("the server did not see one request", 1, seen)
    }

    @Test
    fun `an interim 100 Continue is skipped rather than answered`() {
        // The real edge sends this before a large POST's final answer.
        // Treating it as the answer yields a 1xx status, which is not a
        // success, and an upload reported as refused after it had in fact
        // been accepted.
        LocalEdge(body = 0, sendContinueFirst = true).use { edge ->
            MeasuredConnection(host = "127.0.0.1", port = edge.port).use { connection ->
                connection.connect(1024 * 1024, 5_000, 5_000, tlsFactory = trustAnything())
                val result = connection.timedExchange("/__up")
                assertEquals(
                    "the interim reply was treated as the answer",
                    0L,
                    result.bytes,
                )
            }
        }
    }

    @Test
    fun `a short body is reported as the bytes that arrived`() {
        // The first version of this test asserted that a truncated body
        // would make `timedExchange` fail. It does not, and it should
        // not: `timedExchange` is the *latency* exchange, whose body is
        // a fixed small blob and where a short read simply means a short
        // round trip.
        //
        // The guarantee that matters is elsewhere. Throughput goes
        // through `TransferCheck.reject`, which compares what was declared
        // against what arrived and returns `TRUNCATED` — so a partial
        // download is rejected rather than published as a figure for a
        // transfer that did not happen. That is covered where it lives,
        // in `ProtocolTest`.
        //
        // What this asserts is the layer's actual contract: the count is
        // the truth about the socket, not about the promise in the head.
        LocalEdge(body = 1024, truncateTo = 512).use { edge ->
            MeasuredConnection(host = "127.0.0.1", port = edge.port).use { connection ->
                connection.connect(1024 * 1024, 5_000, 5_000, tlsFactory = trustAnything())
                val result = connection.timedExchange("/__down?bytes=1024")
                assertEquals(
                    "the byte count must be what arrived, not what was promised",
                    512L,
                    result.bytes,
                )
            }
        }
    }

    @Test
    fun `a request to a port with nothing on it is refused, not hung`() {
        val closed = ServerSocket(0, 1, InetAddress.getByName("127.0.0.1"))
        val port = closed.localPort
        closed.close()
        var failure: TransportFailure? = null
        try {
            MeasuredConnection(host = "127.0.0.1", port = port).use { connection ->
                connection.connect(1024 * 1024, 2_000, 2_000, tlsFactory = trustAnything())
            }
        } catch (e: TransportException) {
            failure = e.failure
        }
        assertEquals(
            "a closed port must be refused, not reported as something else",
            TransportFailure.REFUSED,
            failure,
        )
    }

    // ----------------------------------------------------------------- helpers

    private data class BufferCeilingProbe(val granted: Int)

    /**
     * A TLS server that behaves like the edge, on demand.
     *
     * Every knob here exists because a real edge does that thing
     * occasionally and a test has to be able to do it on purpose.
     */
    private class LocalEdge(
        private val body: Int,
        private val sendContinueFirst: Boolean = false,
        private val truncateTo: Int? = null,
    ) : AutoCloseable {
        private val server: SSLServerSocket =
            serverContext.serverSocketFactory.createServerSocket(0, 1, InetAddress.getByName("127.0.0.1")) as SSLServerSocket

        private val served = CountDownLatch(1)

        @Volatile
        var requests: Int = 0
            private set

        val port: Int get() = server.localPort

        init {
            Thread({
                try {
                    val socket = server.accept() as SSLSocket
                    socket.soTimeout = 5_000
                    // Read the request head so the client is not blocked
                    // writing into a socket nobody is reading.
                    val reader = socket.getInputStream().bufferedReader()
                    var line = reader.readLine()
                    while (line != null && line.isNotEmpty()) {
                        line = reader.readLine()
                    }
                    requests++
                    val out = socket.getOutputStream()
                    if (sendContinueFirst) {
                        out.write(
                            ("HTTP/1.1 100 Continue\r\n\r\n").toByteArray(),
                        )
                        out.flush()
                    }
                    val sent = truncateTo ?: body
                    out.write(
                        buildString {
                            append("HTTP/1.1 200 OK\r\n")
                            append("Content-Length: ").append(body).append("\r\n")
                            append("Content-Type: application/octet-stream\r\n")
                            append("\r\n")
                        }.toByteArray(),
                    )
                    val chunk = ByteArray(8 * 1024) { (it % 251).toByte() }
                    var written = 0
                    while (written < sent) {
                        val n = minOf(chunk.size, sent - written)
                        out.write(chunk, 0, n)
                        written += n
                    }
                    out.flush()
                    socket.close()
                } catch (_: Exception) {
                    // A test that closes early is a test that passed for
                    // the right reason only if the assertions still run.
                } finally {
                    served.countDown()
                }
            }, "pulsekraft-test-edge").apply { isDaemon = true }.start()
        }

        override fun close() {
            runCatching { server.close() }
            served.await(2, TimeUnit.SECONDS)
        }
    }

    /**
     * Trusts the throwaway certificate.
     *
     * Only ever used against a server this test started on the loopback
     * interface, in a process that exists for the length of the test.
     */
    private fun trustAnything(): javax.net.ssl.SSLSocketFactory =
        SSLContext.getInstance("TLS").apply {
            init(null, arrayOf<TrustManager>(TrustEverything), java.security.SecureRandom())
        }.socketFactory

    private object TrustEverything : X509TrustManager {
        override fun checkClientTrusted(
            chain: Array<java.security.cert.X509Certificate>?,
            authType: String?,
        ) = Unit

        override fun checkServerTrusted(
            chain: Array<java.security.cert.X509Certificate>?,
            authType: String?,
        ) = Unit

        override fun getAcceptedIssuers(): Array<java.security.cert.X509Certificate> =
            emptyArray()
    }
}